version: '3.3'
services:
  mysql:
    image: mysql:5.7.28
    hostname: "mysql"
    environment:
      - MYSQL_USER=coachee_user
      - MYSQL_PASSWORD=coachee_pass
      - MYSQL_DATABASE=coachee_db
      - MYSQL_ROOT_PASSWORD=coachee_pass
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
  coachee:
    build:
      context: .
      dockerfile: Dockerfile
    image: pmdcosta/coachee:latest
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=coachee_user
      - DB_PASSWORD=coachee_pass
      - DB_NAME=coachee_db
      - EMAIL_USERNAME=joaotest76@gmail.com
      - EMAIL_PASSWORD=Matematica123
    ports:
      - 8080:80
    command: -domain 127.0.0.1
