version: '3.3'
services:
  mysql:
    image: mysql:5.7.28
    hostname: "mysql"
    environment:
      - MYSQL_USER=coachee_user
      - MYSQL_PASSWORD=coachee_pass
      - MYSQL_DATABASE=coachee_db
      - MYSQL_ROOT_PASSWORD=coachee_pass
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
      - 33060:33060
  coachee:
    build:
      context: .
      dockerfile: Dockerfile
    image: pmdcosta/coachee:latest
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=coachee_user
      - DB_PASSWORD=coachee_pass
      - DB_NAME=coachee_db
    ports:
      - 80:80
    command: -domain 0.0.0.0
