version: '3.3'
services:
  mysql:
    image: mysql:5.7.
    restart: always
    hostname: "mysql"
    env_file:
      - ./.env
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
  coachee:
    build:
      context: .
      dockerfile: Dockerfile
    image: pmdcosta/coachee:latest
    restart: always
    depends_on:
      - mysql
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:8080:8080"
    command: -http-port 8080 -domain 0.0.0.0
